kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-viewer-fvdyi

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-viewer-fvdyi
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-viewer-fvdyi
  namespace: default
subjects:
- kind: ServiceAccount
  name: account-default-viewer-fvdyi
  namespace: default
roleRef:
  kind: Role
  name: role-default-viewer-fvdyi
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-viewer
rules:
  - apiGroups: ["chaos-mesh.org"]
    resources: ["schedules"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: account-default-viewer-fvdyi
    namespace: default  # Replace with the correct namespace if needed
roleRef:
  kind: ClusterRole
  name: chaos-mesh-viewer  # This should match the name of the ClusterRole you just created
  apiGroup: rbac.authorization.k8s.io
