apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-mesh-namespace-role
  namespace: default  # Ensure this is the correct namespace
rules:
  - apiGroups: ["chaos-mesh.org"]
    resources: ["jvmchaos"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-kernelchaos-viewer
rules:
  - apiGroups: ["chaos-mesh.org"]
    resources: ["kernelchaos"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]



---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-mesh-rolebinding
  namespace: default  # Ensure this matches the namespace where the issue is happening
subjects:
  - kind: ServiceAccount
    name: account-default-viewer-fvdyi
    namespace: default  # The namespace of your service account
roleRef:
  kind: Role
  name: chaos-mesh-namespace-role  # The name of the Role we just created
  apiGroup: rbac.authorization.k8s.io
