apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-full-access
rules:
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]  # This will grant permissions for all resources in the chaos-mesh.org API group
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-full-access-binding
subjects:
  - kind: ServiceAccount
    name: account-default-manager-monkey  # Replace with your actual service account
    namespace: default
roleRef:
  kind: ClusterRole
  name: chaos-mesh-full-access
  apiGroup: rbac.authorization.k8s.io
