apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-spring-boot
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default 
    labelSelectors:
      app: springboot-helloworld-deployment
  duration: '30s' 
  scheduler:
    cron: '@every 1m'