apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: springboot-helloworld-gateway
spec:
  selector:
    istio: ingressgateway # Use Istio's ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: springboot-helloworld-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - springboot-helloworld-gateway
  http:
  - route:
    - destination:
        host: springboot-helloworld-service
        port:
          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: springboot-helloworld-service-destination-rule
spec:
  host: springboot-helloworld-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 1 # Number of 5xx errors to trigger circuit breaking
      interval: 1s # Time window to evaluate errors
      baseEjectionTime: 500s # Minimum time the service is ejected from the pool
      maxEjectionPercent: 100 # Maximum % of hosts ejected from the pool