apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-helloworld-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: springboot-helloworld
  template:
    metadata:
      labels:
        app: springboot-helloworld
    spec:
      containers:
        - name: springboot-helloworld
          image: southamerica-west1-docker.pkg.dev/dryruns/springboot-helloworld/springboot-helloworld:latest # Use the correct image tag
          ports:
            - containerPort: 8080 # Expose the port your Spring Boot app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld-service
spec:
  selector:
    app: springboot-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Map the service port to the container port
  type: LoadBalancer # Or use NodePort if you don't need external access