apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-helloworld-deployment
  annotations:
    chaos-mesh.org/inject-chaos-mesh-agent: "true"
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: springboot-helloworld
  template:
    metadata:
      labels:
        app: springboot-helloworld
    spec:
      containers:
        - name: springboot-helloworld
          image: southamerica-west1-docker.pkg.dev/dryruns/springboot-helloworld/springboot-helloworld:latest
          ports:
            - containerPort: 8080 
          env:
              - name: DEGRADE_AFTER_SECONDS
                valueFrom:
                  configMapKeyRef:
                    key: degradeAfterSeconds
                    name: degradation-config
              - name: DEGRADE
                valueFrom:
                  configMapKeyRef:
                    key: degrade
                    name: degradation-config
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld-service
spec:
  selector:
    app: springboot-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  type: LoadBalancer